### ISSUE TITLE
Cannot test by changing platform from flutter inspector 

### ISSUE THREAD

**Issue by PifeVoxd** [joshuadeguzman/flutter_dialogs#2]
Hello,

So I was trying to test how my app would look on both Android and IOS using this library, but while all my other widgets changed to their platform specific look just by switching the platform from the flutter inspector in Android Studio, the dialogs (created using this library) don't. I looked trough the code and i suspect it is because you are using the `dart::io` library in platform_dialog.dart, `Theme.of(context).platform` should be used instead, this would allow for greater flexibility and for making sure the dialog looks right just by switching the platform from the flutter inspector.

Thanks!

**Comment by PifeVoxd** [comment]
Hello @joshuadeguzman,

I'm sorry to bother you again, but maybe you didn't see this issue, or were not notified.
I hope that by tagging you, you will be notified.

Thanks!

**Comment by joshuadeguzman** [comment]
Hey @PifeVoxd, I have uploaded a new version on Pub, thank you!
