### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by Vincent-76** [joshuadeguzman/flutter_dialogs#7]
Please migrate this plugin to null safety. Thank you.

**Comment by gilescm** [comment]
Is there any news on this? Would be great to have this package migrated 🚀

**Comment by joshuadeguzman** [comment]
Sure, I will migrate this over the weekend. Thanks!

**Comment by haydgately** [comment]
Has there been any progress on this @joshuadeguzman  ? :)

**Comment by Bersh** [comment]
Take a look https://github.com/joshuadeguzman/flutter_dialogs/pull/8
